version: '3.8'

services:
  backend:
    image: node:18-alpine
    container_name: cv-validator-backend
    working_dir: /app
    command: sh -c "npm install --legacy-peer-deps && npm run dev:watch"
    env_file:
      - .env.config
    environment:
      # Construct DATABASE_URL from individual parameters
      DATABASE_URL: postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?sslmode=require
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      PORT: 3001
      NODE_ENV: development
      FRONTEND_URL: http://localhost:3000
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
      - uploads_data:/app/uploads
    networks:
      - cv-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    image: node:18-alpine
    container_name: cv-validator-frontend
    working_dir: /app
    command: sh -c "npm install --legacy-peer-deps && npm run dev"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
      - /app/.next
    depends_on:
      - backend
    networks:
      - cv-network
    restart: unless-stopped

volumes:
  backend_node_modules:
  frontend_node_modules:
  uploads_data:

networks:
  cv-network:
    driver: bridge 